package com.example.springboot.logger;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
public class SpringbootLoggerApplication {

    private static final Logger logger = LoggerFactory.getLogger(SpringbootLoggerApplication.class);

    public static void main(String[] args) {
        logger.info("appplication start begin!");
        SpringApplication.run(SpringbootLoggerApplication.class, args);
        logger.info("appplication start end!");
    }

}
